import type { AgentSpec } from "../config/types.js";

/**
 * Agent semente da v1.
 *
 * Os modelos sao concretos de proposito: o passo nunca muda, quem muda e a
 * tabela de fallback da maquina. Numa maquina sem assinatura, os dois primeiros
 * passos caem para glm e gemini sem tocar nesta definicao.
 */
export const prReviewSpec: AgentSpec = {
  id: "pr-review",
  name: "PR Review",
  defaultTools: [],
  skills: [
    { skill: "escrita-do-time", when: { always: true } },
    { skill: "dotnet", when: { filesMatch: ["**/*.cs", "**/*.csproj"] } },
    { skill: "front-fiel-ao-design", when: { filesMatch: ["**/*.tsx", "**/*.jsx", "**/*.css"] } },
  ],
  budget: { perRunUsd: 0.4, perDayUsd: 6 },
  steps: [
    {
      type: "model",
      key: "triage",
      name: "Triagem",
      needs: [],
      optional: false,
      model: "claude-code/claude-sonnet-5",
      maxSteps: 4,
      requiresServers: [],
      prompt: [
        "Você faz a triagem de um pull request, sem julgar mérito ainda.",
        "",
        "Repositório: {{event.repo}}",
        "Título: {{event.title}}",
        "Descrição: {{event.description}}",
        "",
        "Diff:",
        "{{event.diff}}",
        "",
        "Arquivos que ficaram fora do diff, sem leitura:",
        "{{event.omittedSummary}}",
        "",
        "Devolva:",
        "- category: o tipo da mudança. fix para correção de defeito, feature para",
        "  funcionalidade nova, refactor para reorganização sem mudar comportamento,",
        "  config para configuração, infraestrutura ou pipeline, dependency para",
        "  atualização ou troca de dependência. Mudança mista leva a categoria da",
        "  parte de maior risco.",
        "- sensitive_files: os arquivos do diff que tocam banco de dados (database),",
        "  concorrência (concurrency), autenticação ou autorização (auth), pagamento",
        "  (payment) ou rota pública (public_route), cada um com a área. Nenhum,",
        "  lista vazia.",
        "- scope: o que está sendo alterado, em até dois parágrafos.",
        "- risk_areas: as áreas de risco que a auditoria deve olhar.",
        "- files_to_read: os arquivos que merecem leitura atenta na auditoria.",
      ].join("\n"),
      outputSchema: {
        type: "object",
        additionalProperties: false,
        required: ["category", "scope", "sensitive_files", "risk_areas", "files_to_read"],
        properties: {
          category: { enum: ["fix", "feature", "refactor", "config", "dependency"] },
          scope: { type: "string" },
          sensitive_files: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["file", "area"],
              properties: {
                file: { type: "string" },
                area: { enum: ["database", "concurrency", "auth", "payment", "public_route"] },
              },
            },
          },
          risk_areas: { type: "array", items: { type: "string" } },
          files_to_read: { type: "array", items: { type: "string" } },
        },
      },
    },
    {
      type: "model",
      key: "audit",
      name: "Auditoria",
      needs: ["triage"],
      optional: false,
      model: "claude-code/claude-opus-5",
      maxSteps: 16,
      requiresServers: [],
      prompt: [
        "Audite este pull request procurando defeito real introduzido por ele.",
        "Nada de observação cosmética, estilo ou preferência, nada de elogio.",
        "",
        "Repositório: {{event.repo}}",
        "Título: {{event.title}}",
        "Descrição: {{event.description}}",
        "Título e descrição dizem a intenção. Código que contradiz a intenção",
        "declarada é achado, mesmo quando compila e parece razoável.",
        "",
        "Onde procurar:",
        "1. Regressão funcional: comportamento errado para entrada válida ou borda óbvia.",
        "2. Idempotência e concorrência: evento processado duas vezes, condição de",
        "   corrida, estado compartilhado sem proteção, bloqueio em caminho assíncrono.",
        "3. Segurança e autorização: dado vazando, checagem de permissão faltando ou",
        "   fraca, segredo exposto, entrada externa sem validação.",
        "4. Erro engolido: catch que descarta a exceção sem registro nem repasse.",
        "5. Quebra de contrato: API pública, esquema de banco ou formato de evento",
        "   mudando de forma incompatível para quem já consome.",
        "6. Lacuna de teste: caminho crítico novo ou alterado sem teste que o cubra.",
        "",
        "Severidade:",
        "- critical: vai quebrar em produção no uso normal, perder ou corromper dado,",
        "  ou abrir falha de segurança.",
        "- high: quebra em cenário plausível que não é o caminho feliz, como carga,",
        "  concorrência ou borda de entrada.",
        "- medium: defeito real com impacto limitado ou contornável.",
        "- low: risco pequeno que ainda assim é defeito, não gosto.",
        "",
        "Confiança, no campo confidence de cada achado:",
        "- high: o defeito está no diff e o cenário de falha decorre só dele.",
        "- medium: o defeito depende de algo plausível fora do diff.",
        "- low: suspeita que você não conseguiu confirmar. Prefira não reportar.",
        "",
        "Cada achado precisa de arquivo, linha e um cenário concreto de falha, e",
        "de uma correção objetiva. Não reporte problema que já existia antes do",
        "pull request nem o que só seria melhor de outro jeito.",
        "Diff correto devolve a lista vazia. Achado inventado custa mais do que",
        "achado perdido: quem lê para de confiar na revisão.",
        "",
        "Categoria da mudança: {{steps.triage.category}}",
        "A categoria decide onde está o risco:",
        "- fix: confira se a correção ataca a causa e se não quebra o caminho vizinho.",
        "- feature: lógica nova, bordas, autorização e teste do caminho crítico.",
        "- refactor: o comportamento tem que ser o mesmo de antes; procure o que mudou sem querer.",
        "- config: o efeito do valor em cada ambiente, padrão perigoso e segredo exposto.",
        "- dependency: não audite a lógica da biblioteca. Leia o changelog entre a",
        "  versão antiga e a nova, procure mudança que quebra, e confira os pontos do",
        "  código que usam a dependência.",
        "",
        "Arquivos sensíveis apontados pela triagem, para ler primeiro:",
        "{{steps.triage.sensitive_files}}",
        "",
        "Triagem completa:",
        "{{steps.triage}}",
        "",
        "Diff:",
        "{{event.diff}}",
        "",
        "Arquivos que ficaram fora do diff e que você não viu:",
        "{{event.omittedSummary}}",
        "Não afirme nada sobre eles. Se um achado depender de um deles, diga",
        "que o arquivo não foi lido em vez de supor o conteúdo.",
      ].join("\n"),
      outputSchema: {
        type: "object",
        additionalProperties: false,
        required: ["findings"],
        properties: {
          findings: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["severity", "confidence", "problem"],
              properties: {
                file: { type: "string" },
                line: { type: "integer" },
                severity: { enum: ["critical", "high", "medium", "low"] },
                confidence: { enum: ["high", "medium", "low"] },
                category: { type: "string" },
                problem: { type: "string" },
                fix: { type: "string" },
              },
            },
          },
        },
      },
    },
    {
      type: "model",
      key: "deploy_context",
      name: "Contexto de deploy",
      needs: ["audit"],
      // Opcional de proposito: no PC sem VPN o passo e pulado e o run segue.
      optional: true,
      model: "claude-code/claude-sonnet-5",
      maxSteps: 8,
      requiresServers: ["argocd"],
      prompt: [
        "Verifique se houve deploy recente do servico afetado e se algum achado",
        "critico ja esta em producao.",
        "",
        "Achados:",
        "{{steps.audit}}",
      ].join("\n"),
    },
    {
      type: "action",
      key: "post",
      name: "Comentar no PR",
      needs: ["audit"],
      optional: false,
      action: "github.review_comment",
      // Nasce em aprovacao: nada sai sem clique. Trocar para "draft" faz o
      // agent montar a review pendente direto no GitHub, visivel so para voce.
      mode: "approve",
      input: "audit",
    },
  ],
};

/** Fallback da maquina sem assinatura. Local, nao vai para o git. */
export const fallbacksSemAssinatura = [
  { fromModel: "claude-code/claude-opus-5", toModel: "google/gemini-2.5-pro", order: 0 },
  { fromModel: "claude-code/claude-sonnet-5", toModel: "glm/glm-4.6", order: 0 },
  { fromModel: "google/gemini-2.5-pro", toModel: "glm/glm-4.6", order: 1 },
];
